# Generated by Django 3.2.9 on 2021-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211104_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='0', max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Hard', 'Сложно'), ('Easy', 'Легко'), ('Medium', 'Средне')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
    ]
