# Generated by Django 3.2.9 on 2021-11-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211104_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=255, verbose_name='Название категории блюда')),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='productstype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории продукта'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dishType',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.dishtype'),
        ),
    ]
