# Generated by Django 3.2.9 on 2021-11-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211104_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Medium', 'Средне'), ('Hard', 'Сложно'), ('Easy', 'Легко')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории блюда'),
        ),
    ]
