# Generated by Django 3.2.9 on 2021-11-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211104_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='dishName',
        ),
        migrations.RenameField(
            model_name='dishtype',
            old_name='name',
            new_name='dishTypeName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='productstype',
            old_name='name',
            new_name='productTypeName',
        ),
    ]
