# Generated by Django 3.2.9 on 2021-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211104_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dishType',
            new_name='dishTtype',
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Hard', 'Сложно'), ('Medium', 'Средне')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
    ]
