# Generated by Django 3.2.9 on 2021-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211104_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Hard', 'Сложно'), ('Medium', 'Средне'), ('Easy', 'Легко')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
    ]
