# Generated by Django 3.2.9 on 2021-11-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dish_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('Medium', 'Средне'), ('Hard', 'Сложно'), ('Easy', 'Легко')], default='Легко', max_length=10, verbose_name='Сложность'),
        ),
    ]
